apiVersion: v2
name: rocket
description: Go fast!
version: 1.0.0
appVersion: 9.17.49
icon: https://wile.example.com/rocket.svg
keywords:
  - road runner
  - rocket
home: https://wile.example.com/
sources:
  - https://github.com/masterminds/learning-helm/blob/master/chapter7/rocket
maintainers:
  - name: ACME Corp
    email: maintainers@example.com
  - name: Wile E. Coyote
    email: wile@example.com
dependencies:
  - name: booster
    version: ^1.0.0
    repository: https://raw.githubusercontent.com/Masterminds/learning-helm/master/chapter7/repository/